import { DefaultTheme } from 'react-native-paper';
import { ThemeType, AppTheme } from '../types/theme';

export const themes: Record<ThemeType, AppTheme> = {
    pink: {
        ...DefaultTheme,
        colors: {
            ...DefaultTheme.colors,
            primary: '#E6A4B4',
            accent: '#B8D8E3',
            background: '#FFFFFF',
            surface: '#F8F8F8',
            error: '#FF7F7F',
            text: '#000000',
            placeholder: '#888888',
            backdrop: 'rgba(0, 0, 0, 0.5)',
            notification: '#E6A4B4',
            onSurface: '#000000',
            cardBackground: '#FFFFFF',
            dialogBackground: '#FFFFFF',
            calendarDot: '#E6A4B4',
            calendarSelected: '#E6A4B4',
            calendarToday: '#E6A4B4',
            switchTrackTrue: '#E6A4B4',
            fabBackground: '#E6A4B4',
        },
    },
    blue: {
        ...DefaultTheme,
        colors: {
            ...DefaultTheme.colors,
            primary: '#89CFF0',
            accent: '#CCE5FF',
            background: '#FFFFFF',
            surface: '#F8F8F8',
            error: '#FF7F7F',
            text: '#000000',
            placeholder: '#888888',
            backdrop: 'rgba(0, 0, 0, 0.5)',
            notification: '#89CFF0',
            onSurface: '#000000',
            cardBackground: '#FFFFFF',
            dialogBackground: '#FFFFFF',
            calendarDot: '#89CFF0',
            calendarSelected: '#89CFF0',
            calendarToday: '#89CFF0',
            switchTrackTrue: '#89CFF0',
            fabBackground: '#89CFF0',
        },
    },
    orange: {
        ...DefaultTheme,
        colors: {
            ...DefaultTheme.colors,
            primary: '#FFB347',
            accent: '#FFE4B5',
            background: '#FFFFFF',
            surface: '#F8F8F8',
            error: '#FF7F7F',
            text: '#000000',
            placeholder: '#888888',
            backdrop: 'rgba(0, 0, 0, 0.5)',
            notification: '#FFB347',
            onSurface: '#000000',
            cardBackground: '#FFFFFF',
            dialogBackground: '#FFFFFF',
            calendarDot: '#FFB347',
            calendarSelected: '#FFB347',
            calendarToday: '#FFB347',
            switchTrackTrue: '#FFB347',
            fabBackground: '#FFB347',
        },
    },
};

export const themeNames: Record<ThemeType, string> = {
    pink: '粉色主题',
    blue: '蓝色主题',
    orange: '橙色主题',
};
